name: Personal CV workflow
on:
  push:
    branches:
      - master

jobs:

  build_push_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./personal_cv
          file: ./personal_cv/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/personal-cv:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_dockerhub
    steps:
      - name: Execute remote SSH commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker compose down
            sudo docker compose pull ${{ secrets.DOCKER_USERNAME }}/personal-cv:v1
            echo -e "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}\nCHAT_ID=${{ secrets.CHAT_ID }}" >> ./app/.streamlit/secrets.toml
            sudo docker compose up -d

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!
