[theme]
base = "dark"
backgroundColor = "#242424"
secondaryBackgroundColor = "#1d1d1d"

[browser]
serverAddress = "127.0.0.1"
serverPort = 8501
gatherUsageStats = true

[server]
address = "127.0.0.1"
port = 8501
runOnSave = true
enableCORS = true
enableXsrfProtection = true

[logger]
level = "INFO"
messageFormat = "%(asctime)s - %(levelname)s - %(message)s"

[client]
toolbarMode = "minimal"
showErrorDetails = "stacktrace"
showSidebarNavigation = true
