[theme]
base = "dark"
backgroundColor = "#242424"
secondaryBackgroundColor = "#1d1d1d"
textColor = "#f5f5dc"

[browser]
serverAddress = "127.0.0.1"
serverPort = 8501

[server]
address = "127.0.0.1"
port = 8501
baseUrlPath = "amerkulovcv"

[logger]
level = "INFO"
messageFormat = "%(asctime)s - %(levelname)s - %(message)s"
